import chalk from 'chalk';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { getConfigDir, loadConfig } from '../core/config';

export async function startCommand() {
  try {
    console.log(chalk.blue('Starting database introspection...'));

    // Load configuration
    const config = loadConfig();
    const configDir = getConfigDir();

    // Create Prisma schema file
    const schemaPath = path.join(configDir, 'schema.prisma');
    
    let schemaContent = `// This file was auto-generated by db-ai
// It contains the database schema pulled from your database

generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/.prisma/client"
}

datasource db {
  provider = "${config.provider}"`;

    // Add schema configuration for PostgreSQL and SQL Server if provided
    if (config.schema && (config.provider.toLowerCase() === 'postgresql' || config.provider.toLowerCase() === 'postgres' || config.provider.toLowerCase() === 'sqlserver' || config.provider.toLowerCase() === 'mssql')) {
      schemaContent += `\n  schemas = ["${config.schema}"]`;
    }

    schemaContent += `\n}\n`;

    fs.writeFileSync(schemaPath, schemaContent, 'utf-8');
    console.log(chalk.green(`✓ Created schema.prisma at ${schemaPath}`));

    // Run prisma db pull to introspect the database
    // Prisma 7 reads datasource.url from prisma.config.ts automatically
    console.log(chalk.blue('Pulling database schema...'));
    try {
      execSync('npx prisma db pull', {
        cwd: configDir,
        stdio: 'inherit',
      });
      console.log(chalk.green('✓ Database schema pulled successfully'));
    } catch (error: any) {
      console.error(chalk.red('Error pulling database schema:'), error.message);
      console.log(chalk.yellow('Make sure you have the correct database credentials in prisma.config.ts and the database is accessible.'));
      throw error;
    }

    // Generate Prisma Client
    // Prisma 7 reads datasource.url from prisma.config.ts automatically
    console.log(chalk.blue('Generating Prisma Client...'));
    try {
      execSync('npx prisma generate', {
        cwd: configDir,
        stdio: 'inherit',
      });
      console.log(chalk.green('✓ Prisma Client generated successfully'));
    } catch (error: any) {
      console.error(chalk.red('Error generating Prisma Client:'), error.message);
      throw error;
    }

    console.log(chalk.green('\n✓ Database introspection complete!'));
    console.log(chalk.cyan(`\nSchema file: ${schemaPath}`));
    console.log(chalk.cyan('You can now use "db-ai run" to execute queries.'));

  } catch (error: any) {
    console.error(chalk.red('Error during database introspection:'), error.message);
    process.exit(1);
  }
}

